apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: practica_final_backend
  annotations:
    github.com/project-slug: ycordovac/practica_final_backend
spec:
  type: other
  lifecycle: unknown
  owner: guests
